---
xdg: False
auto_start: False

keymap:
  recommended: True

  manual_complete: <c-space>
  bigger_preview: <c-k>
  jump_to_mark: <c-h>

match:
  unifying_chars:
    - "_"
    - "-"
  max_results: 33
  proximate_lines: 16
  exact_matches: 2
  look_ahead: 2
  fuzzy_cutoff: 0.6

weights:
  prefix_matches: 2.0
  edit_distance: 1.5
  recency: 1.0
  proximity: 0.5

display:
  pum:
    fast_close: True

    y_max_len: 16
    y_ratio: 0.3

    x_max_len: 66
    x_truncate_len: 12

    ellipsis: …
    kind_context:
      - " ["
      - "]"
    source_context:
      - "「"
      - "」"

    icons: null

  preview:
    x_max_len: 88
    resolve_timeout: 0.09
    border: rounded
    positions:
      north: 1
      south: 2
      west: 3
      east: 4

  mark_highlight_group: Pmenu

  icons:
    mode: decorate
    aliases: {}
    mappings: {}

limits:
  index_cutoff: 333333
  idle_timeout: 1.88

  completion_auto_timeout: 0.088
  completion_manual_timeout: 0.66

  download_retries: 6
  download_timeout: 66.0

clients:
  tabnine:
    enabled: False
    short_name: "T9"
    weight_adjust: -0.3

  tmux:
    enabled: True
    short_name: "TMUX"
    match_syms: False
    weight_adjust: 0

  buffers:
    enabled: True
    short_name: "BUF"
    match_syms: False
    same_filetype: False
    weight_adjust: 0

  tree_sitter:
    enabled: True
    short_name: "TS"
    path_sep: " ⇊"
    weight_adjust: 0

  paths:
    enabled: True
    short_name: "PATH"
    preview_lines: 6
    path_seps: []
    weight_adjust: 0

  snippets:
    enabled: True
    short_name: "SNIP"
    weight_adjust: 0
    sources: []

  tags:
    enabled: True
    short_name: "TAG"
    match_syms: True
    parent_scope: " ⇊"
    path_sep: " ⇉ "
    weight_adjust: 0

  lsp:
    enabled: True
    short_name: "LSP"
    resolve_timeout: 0.06
    weight_adjust: 0.3
