---
name: CI

on:
  push:
  schedule:
    - cron: "0 0 * * *" # daily

jobs:
  mypy:
    strategy:
      matrix:
        python_ver:
          - "3.x"
          - "3.10"
          - "3.9"
          - "3.8"
          - "3.8.2"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_ver }}

      - name: Pip Packages
        run: pip install --upgrade codespell mypy types-PyYAML -r requirements.txt

      - name: Apt Packages
        run: sudo apt install -y universal-ctags

      - name: Codespell
        run: codespell --skip ./artifacts/helo.yml

      - name: Lint
        run: mypy -- .

      - name: Install
        run: python3 -m coq deps

      - name: Test
        run: python3 -m tests
